export const KEYBOARD_TOUCHDOWN = 'KEYBOARD_TOUCHDOWN'
export const KEYBOARD_TOUCHUP = 'KEYBOARD_TOUCHUP'
export const KEYBOARD_TOUCHPRESS = 'KEYBOARD_TOUCHPRESS'
export const KEYBOARD_SWITCH = 'KEYBOARD_SWITCH'
