export { default as GOOGLE_ICON } from '@/assets/icons/google.svg?raw'
export { default as RESET_ICON } from '@/assets/icons/reset.svg?raw'
export { default as KEYBOARD_ICON } from '@/assets/icons/keyboard.svg?raw'
export { default as FULLSCREEN_ICON } from '@/assets/icons/fullscreen.svg?raw'
export { default as SCREENSHOT_ICON } from '@/assets/icons/screenshot.svg?raw'
export { default as UPLOAD_ARCHIVE_ICON } from '@/assets/icons/upload.svg?raw'
export { default as DOWNLOAD_ARCHIVE_ICON } from '@/assets/icons/download.svg?raw'
