name: gh-pages.workflow

on:
  push:
    branches:
      - "main"

jobs:
  gh-pages:
    name: gh-pages
    runs-on: macOS-latest
    steps:
      - name: Initialize projects
        uses: dumlj/dumlj-workflows/.github/actions/setup.node@main
        with:
          node_version: '20'
          git_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build gh-pages
        shell: bash
        run: npm run ci:pages
        env:
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      - name: Release
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
